<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net48</TargetFramework><RootNamespace>EForm.ImportDocument.Infrastructure</RootNamespace><LangVersion>latest</LangVersion></PropertyGroup><ItemGroup><ProjectReference Include="..\EForm.ImportDocument.Domain\EForm.ImportDocument.Domain.csproj" /></ItemGroup><ItemGroup><PackageReference Include="Ninject" Version="3.3.6"/><PackageReference Include="Ninject.Web.Common" Version="5.2.1"/><PackageReference Include="EntityFramework" Version="6.4.4"/><PackageReference Include="MySql.Data" Version="8.0.33"/></ItemGroup></Project>
