<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>Module.ImportDocument.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Services\*.cs" />
    <Compile Include="DTOs\*.cs" />
    <Compile Include="Interfaces\*.cs" />
    <ProjectReference Include="..\Domain\Module.ImportDocument.Domain.csproj" />
  </ItemGroup>
</Project>
