<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>Module.ImportDocument.Domain</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ImportField.cs" />
    <Compile Include="ImportResponse.cs" />
  </ItemGroup>
</Project>
